name: autobind
channels:
  - conda-forge
dependencies:
  - python=3.9

  # core
  - numpy
  - pip

  # metallicious deps (as per their install instructions)
  - rdkit
  - parmed
  - autode
  - psiresp
  - mdanalysis
  - networkx
  - qcelemental=0.25.1
  - ambertools

  # pip installs last
  - pip:
      - metallicious
      - typer
      - -e .
